@echo off
echo Starting TrackMan Development Server...
echo.
echo Starting Backend Server...
start "Backend Server" cmd /k "npm run server:dev"
echo.
echo Starting Frontend Client...
start "Frontend Client" cmd /k "npm run client:dev"
echo.
echo Both servers are starting in separate windows...
echo Close this window when you're done developing.
pause
